### PR TITLE
fix: add UUID hyphens

### LINKED ISSUE #115: UUID with hyphens
The `UUID` should be generated with hyphens.

```js
import { Binary } from 'bson';
import { toJSString } from 'mongodb-query-parser';
import { v4 as uuidv4 } from 'uuid';

const UUID = uuidv4();
const hex = UUID.split('-').join('');
const buffer = new Buffer.from(hex, 'hex');
const binary = new Binary(buffer, Binary.SUBTYPE_UUID);

const jss = toJSString({ uuidField: binary });
console.log(jss);
```
---
Example with UUID = '38105f18-73f7-4b2d-bdb7-73b0cfafbb2d'
## Actual output:
```console
{
  uuidField: UUID("38105f1873f74b2dbdb773b0cfafbb2d")
}
```

## Expect output:
```console
{
  uuidField: UUID("38105f18-73f7-4b2d-bdb7-73b0cfafbb2d")
}
```

## How to fix
This issue is related to _BSON_TO_JS_STRING_ in https://github.com/mongodb-js/query-parser/blob/master/lib/stringify.js .

```diff
diff --git a/node_modules/mongodb-query-parser/lib/stringify.js b/node_modules/mongodb-query-parser/lib/stringify.js
index 93904b0..fbdc7dc 100644
--- a/node_modules/mongodb-query-parser/lib/stringify.js
+++ b/node_modules/mongodb-query-parser/lib/stringify.js
@@ -49,7 +49,8 @@ const BSON_TO_JS_STRING = {
   Binary: function(v) {
     const subType = v.sub_type;
     if (subType === 4) {
-      return `UUID("${v.buffer.toString('hex')}")`;
+      const uuidHex = v.buffer.toString('hex');
+      return `UUID("${uuidHex.slice(0, 8)}-${uuidHex.slice(8, 12)}-${uuidHex.slice(12, 16)}-${uuidHex.slice(16, 20)}-${uuidHex.slice(20, 32)}")`;
     }
     return `BinData(${subType.toString(16)}, '${v.buffer.toString('base64')}')`;
   },
```

### PR DESCRIPTION
**Pull request by rtritto**
Fix #115

### CODE REVIEW

File: lib/stringify.js [hunk 1]
```diff
@@ -49,7 +49,8 @@ const BSON_TO_JS_STRING = {
   Binary: function(v) {
     const subType = v.sub_type;
     if (subType === 4) {
-      return `UUID("${v.buffer.toString('hex')}")`;
+      const uuidHex = v.buffer.toString('hex');
+      return `UUID("${uuidHex.slice(0, 8)}-${uuidHex.slice(8, 12)}-${uuidHex.slice(12, 16)}-${uuidHex.slice(16, 20)}-${uuidHex.slice(20, 32)}")`;
```
Comment (addaleax) [inline lib/stringify.js:53]: How do we handle this when the UUID is is not a valid UUID (of different length)?

Fwiw, this is how we handle this in mongosh (a bit more complex admittedly): https://github.com/mongodb-js/mongosh/blob/73961583a7afd86f9674e04615eb70ab6d59f1ce/packages/service-provider-core/src/printable-bson.ts#L54-L74

so I would at least add `v.buffer.length === 16` to the `if` above

Comment (rtritto) [reply lib/stringify.js:53]: We should do a difference from `Binary` and `BinData`?
```js
const subType = v.sub_type;
if (subType === 4) {
  if (v.buffer.length === 16) {
    const uuidHex = v.buffer.toString('hex');
    return `UUID("${uuidHex.slice(0, 8)}-${uuidHex.slice(8, 12)}-${uuidHex.slice(12, 16)}-${uuidHex.slice(16, 20)}-${uuidHex.slice(20, 32)}")`;
  }
  return `Binary(Buffer.from("${v.buffer.toString('hex')}", "hex"), ${subType})`;
}
return `BinData(${subType.toString(16)}, '${v.buffer.toString('base64')}')`;
```
Or we should use/correct with one of?

Comment (addaleax) [reply lib/stringify.js:53]: No, I would stick with `BinData` for now until https://jira.mongodb.org/browse/NODE-4855 is addressed, not `Binary` (because `Buffer.from()` is not a thing in Compass right now, and probably shouldn’t be).

My point was just that we shouldn’t use the `UUID()` representation if the buffer isn’t 16 bytes long (e.g. test your code here with an empty `BinData(4, '')` and it should become clear that the representation with dashes doesn’t really work)

Comment (rtritto) [reply lib/stringify.js:53]: Added a commit with the change.

**Comment by addaleax** [comment]
As always, thank your for the PR! `📦  mongodb-query-parser@2.4.11`
